name = "CrystallographyRecipes"
uuid = "6d201c90-cd51-4bcb-ba42-504028e2f5e7"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[deps]
Crystallography = "3bff3928-7a76-11e9-2089-d112443085a5"
CrystallographyBase = "93b1d1cd-a8ea-4aa5-adb1-b2407ea0ba8d"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Crystallography = "0.6"
CrystallographyBase = "0.8, 0.9, 0.10, 0.11, 0.12, 0.13"
RecipesBase = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
